# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'cadull-internal-consumption'
    azureResourceGroup: 'aksnolocal_rg'
    kubernetesCluster: 'aksnolocal'
    command: 'get'
    arguments: 'no'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'